# Generated by Django 5.1.6 on 2025-03-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ecomapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="productinfo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
