# Generated by Django 5.1.6 on 2025-03-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ecomapp", "0002_alter_products_productinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="numreviews",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
