# Generated by Django 5.1.6 on 2025-03-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0003_products_numreviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
