# Generated by Django 5.1.6 on 2025-03-31 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0006_color_size_products_colors_products_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='products',
            name='stockcount',
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockcount', models.IntegerField(blank=True, default=0, null=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecomapp.color')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='Ecomapp.products')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecomapp.size')),
            ],
        ),
    ]
