# Generated by Django 5.1.6 on 2025-03-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0008_size_size_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='gender',
            field=models.CharField(choices=[('boy', 'Boy'), ('girl', 'Girl'), ('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex')], default='unisex', max_length=10),
        ),
    ]
