# Generated by Django 5.1.6 on 2025-03-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0009_products_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='gender',
            field=models.CharField(choices=[('boy', 'Boy'), ('girl', 'Girl'), ('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex')], max_length=10, null=True),
        ),
    ]
